import { test, expect } from "vitest";
import { WebGLGraphicsDevice } from "../../src/graphics/WebGLGraphicsDevice.js";
import { GeissGpuWarp } from "../../src/pipelines/geiss/gpu/GeissGpuWarp.js";
import { warpIntensity8 } from "../../src/pipelines/geiss/reference/FeedbackWarp.js";
import { quantizeMapTexel } from "../../src/pipelines/geiss/reference/MapField.js";
import { createMapParameters } from "../../src/pipelines/geiss/reference/MapParameterFactory.js";
import { MsvcRandom } from "../../src/pipelines/geiss/reference/MsvcRandom.js";

const NOISE = (): Float32Array => new Float32Array(2345);

/** Build a full destination-to-source map for a mode using the CPU oracle. */
const buildMap = (mode: number, width: number, height: number, seed: number) => {
  const params = createMapParameters(mode, width, height, 4, 30, 1, NOISE(), new MsvcRandom(seed));
  const rng = new MsvcRandom(seed * 97 + 1);
  const map = [];
  for (let y = 0; y < height; y++) {
    for (let x = 0; x < width; x++) map.push(quantizeMapTexel(x, y, params, rng));
  }
  return map;
};

const fillSource = (out: Uint8Array, seed: number): void => {
  for (let i = 0; i < out.length; i++) out[i] = (i * 53 + seed * 31) & 255;
};

/**
 * Why: the GPU integer warp is the first classic GPU pass and MUST equal the CPU
 * oracle exactly (Phase 5 gate: "per-pass texture comparisons against CPU oracle").
 * The map is generated by the oracle; the same source is warped on CPU and GPU and
 * compared byte-for-byte across several sizes and seeds.
 */
test("GPU integer warp matches warpIntensity8 byte-for-byte across sizes and seeds", () => {
  for (const [W, H] of [[64, 48], [128, 96]] as const) {
    const canvas = document.createElement("canvas");
    canvas.width = W;
    canvas.height = H;
    const device = new WebGLGraphicsDevice(canvas);
    const warp = new GeissGpuWarp(device, W, H);

    for (const seed of [1, 2, 3, 7, 42, 314]) {
      const map = buildMap(2, W, H, seed);
      warp.setMap(map);

      const src = new Uint8Array(W * H);
      fillSource(src, seed);
      const cpu = new Uint8Array(W * H);
      warpIntensity8(src, cpu, map, W);
      const gpu = warp.warp(src);

      expect(Array.from(gpu), `GPU warp must match CPU at ${W}x${H} seed ${seed}`).toEqual(Array.from(cpu));
      expect(gpu.reduce((s, v) => s + v, 0), `warp produced empty output at seed ${seed}`).toBeGreaterThan(0);
    }

    warp.destroy();
    device.destroy();
  }
});
