#version 300 es
precision highp float;
precision highp int;
precision highp usampler2D;

// Operative WebGL2 exact warp pass. The destination-to-source map is generated by
// the CPU oracle (MapField.quantizeMapTexel) and uploaded as two integer textures.
//
// Feedback is a normalized RGBA8 texture (red = scalar intensity/255) so this pass
// can chain directly from the ping-pong/diminish targets. The byte is recovered
// with +0.5 (value/255 round-trips), keeping the integer math exact. The four taps
// are read by FLAT index to reproduce the CPU oracle's linear framebuffer reads
// EXACTLY, including reads that cross a row boundary (the original C reads
// o, o+1, o+width, o+width+1). 2D texel + ivec2 offsets would diverge at the right
// edge, so flat indexing is a fidelity requirement, not an optimization.
//
// The map textures stay RGBA8UI (exact bytes; sampled, never rendered). The result
// wraps `& 255` to mirror warpIntensity8's Uint8Array store (a no-op once weights
// are a valid convex sum).

uniform sampler2D uFeedback;       // RGBA8 normalized, red = intensity/255
uniform highp usampler2D uMapBase;     // RGBA16UI, rg = source x,y (uint)
uniform highp usampler2D uMapWeights;  // RGBA8UI, rgba = w00,w10,w01,w11 (bytes)
uniform int uWidth;

layout(location = 0) out vec4 outColor;

int fetchFlat(int idx) {
  return int(texelFetch(uFeedback, ivec2(idx % uWidth, idx / uWidth), 0).r * 255.0 + 0.5);
}

void main() {
  ivec2 dest = ivec2(gl_FragCoord.xy);
  uvec2 src = texelFetch(uMapBase, dest, 0).rg;
  int o = int(src.y) * uWidth + int(src.x);

  uvec4 w = texelFetch(uMapWeights, dest, 0);
  int value = (fetchFlat(o)             * int(w.r)
             + fetchFlat(o + 1)         * int(w.g)
             + fetchFlat(o + uWidth)     * int(w.b)
             + fetchFlat(o + uWidth + 1) * int(w.a)) >> 8;

  outColor = vec4(float(value & 255) / 255.0, 0.0, 0.0, 1.0);
}
